# Generated by Django 5.2.4 on 2025-08-01 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionMenee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure", models.TimeField()),
                ("manoeuvre", models.CharField(max_length=200)),
                ("type_reseau", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Cause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_cause", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EquipeAnalyse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("structure", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Equipement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Lieu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle_lieu", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ouvrage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle_ouvrage", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CollecteIncident",
            fields=[
                ("num_inc", models.AutoField(primary_key=True, serialize=False)),
                ("date_inc", models.DateField()),
                ("heure_inc", models.TimeField()),
                ("siege", models.CharField(max_length=100)),
                ("localisation", models.CharField(max_length=100)),
                ("constat", models.CharField(default="RAS", max_length=200)),
                ("fait_avant", models.CharField(max_length=200)),
                ("fait_apres", models.CharField(blank=True, max_length=200, null=True)),
                ("env_atmospherique", models.CharField(default="RAS", max_length=200)),
                ("env_vegeta", models.CharField(default="RAS", max_length=200)),
                ("env_animal", models.CharField(default="RAS", max_length=200)),
                ("env_industriel", models.CharField(default="RAS", max_length=200)),
                ("cause_agression", models.CharField(max_length=200)),
                ("cause_technique", models.CharField(max_length=200)),
                ("reprise_client", models.CharField(max_length=200)),
                ("mes_exploitation", models.CharField(default="RAS", max_length=200)),
                ("mes_maintenance", models.CharField(default="RAS", max_length=200)),
                ("impact_param_qp", models.CharField(max_length=200)),
                ("situation_provisoire", models.CharField(max_length=200)),
                ("action_a_menee", models.CharField(max_length=200)),
                ("autre_info", models.CharField(default="RAS", max_length=200)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.actionmenee",
                    ),
                ),
                (
                    "equipement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.equipement",
                    ),
                ),
                (
                    "lieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.lieu",
                    ),
                ),
                (
                    "ouvrage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.ouvrage",
                    ),
                ),
            ],
        ),
    ]
