# Generated by Django 5.2.4 on 2025-08-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cause",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type_cause", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CollecteIncident",
            fields=[
                (
                    "num_inc",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("date_inc", models.DateField()),
                ("heure_inc", models.TimeField()),
                ("constat", models.CharField(default="RAS", max_length=200)),
                ("fait_avant", models.CharField(max_length=200)),
                ("fait_apres", models.CharField(blank=True, max_length=200, null=True)),
                ("env_atmospherique", models.CharField(default="RAS", max_length=200)),
                ("env_vegeta", models.CharField(default="RAS", max_length=200)),
                ("env_animal", models.CharField(default="RAS", max_length=200)),
                ("env_humain", models.CharField(default="RAS", max_length=200)),
                ("env_industriel", models.CharField(default="RAS", max_length=200)),
                ("cause_agression", models.CharField(max_length=200)),
                ("cause_technique", models.CharField(max_length=200)),
                ("reprise_client", models.CharField(max_length=200)),
                ("mes_exploitation", models.CharField(default="RAS", max_length=200)),
                ("mes_maintenance", models.CharField(default="RAS", max_length=200)),
                ("impact_param_qp", models.CharField(max_length=200)),
                ("situation_provisoire", models.CharField(max_length=200)),
                ("action_a_menee", models.CharField(max_length=200)),
                ("autre_info", models.CharField(default="RAS", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Equipement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Lieu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("libelle_lieu", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ouvrage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("libelle_ouvrage", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TypeReseau",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ActionMenee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("heure", models.TimeField()),
                ("manoeuvre", models.CharField(max_length=200)),
                ("type_reseau", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=200)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.collecteincident",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipeAnalyse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("structure", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.collecteincident",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collecteincident",
            name="equipement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incident_app.equipement",
            ),
        ),
        migrations.AddField(
            model_name="collecteincident",
            name="lieu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="incident_app.lieu"
            ),
        ),
        migrations.AddField(
            model_name="equipement",
            name="ouvrage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="incident_app.ouvrage"
            ),
        ),
        migrations.AddField(
            model_name="collecteincident",
            name="ouvrage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="incident_app.ouvrage"
            ),
        ),
        migrations.CreateModel(
            name="AnalyseIncident",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_analyse", models.DateField()),
                ("heure_dbt_analyse", models.TimeField()),
                ("heure_fin_analyse", models.TimeField()),
                ("impact_nod", models.CharField(max_length=200)),
                ("impact_nip", models.CharField(max_length=200)),
                ("impact_tmc", models.CharField(max_length=200)),
                ("impact_cout", models.CharField(max_length=200)),
                ("impact_autre", models.CharField(max_length=200)),
                ("list_acteurs", models.TextField()),
                ("list_expertise", models.TextField()),
                ("complt_equipment", models.TextField()),
                ("complt_equip_concerne", models.TextField()),
                ("repartition", models.CharField(max_length=100)),
                ("constat", models.TextField()),
                ("jour_constat", models.CharField(default="RAS", max_length=100)),
                ("heure_dbt_constat", models.CharField(default="RAS", max_length=100)),
                ("heure_fin_constat", models.CharField(default="RAS", max_length=100)),
                ("saison_constat", models.CharField(default="RAS", max_length=100)),
                ("complt_espace_env", models.TextField()),
                (
                    "illustration",
                    models.ImageField(
                        blank=True, null=True, upload_to="illustrations/"
                    ),
                ),
                (
                    "cause",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="incident_app.cause",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.collecteincident",
                    ),
                ),
                (
                    "equipement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.equipement",
                    ),
                ),
                (
                    "lieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.lieu",
                    ),
                ),
                (
                    "ouvrage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.ouvrage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommandationAnalyse",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=200)),
                ("responsabilite", models.CharField(max_length=100)),
                ("delai", models.DateField()),
                ("cout", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "analyse_inc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.analyseincident",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuiviIncident",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tenue_delai", models.BooleanField()),
                ("commentaire_tenue_delai", models.TextField(blank=True, null=True)),
                ("efficacite_action", models.BooleanField()),
                ("commentaire_efficacite", models.TextField(blank=True, null=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incident_app.collecteincident",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ouvrage",
            name="type_reseau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="incident_app.typereseau",
            ),
        ),
    ]
