# Generated by Django 5.2.4 on 2025-08-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteincident',
            name='objet',
            field=models.TextField(blank=True, null=True, verbose_name="Objet de l'analyse"),
        ),
        migrations.AddField(
            model_name='collecteincident',
            name='origine_cause_probable',
            field=models.TextField(blank=True, null=True, verbose_name='Origine et cause probable'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='action_a_menee',
            field=models.TextField(blank=True, null=True, verbose_name='Actions à mener'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='autre_info',
            field=models.TextField(blank=True, default='RAS', verbose_name='Autres informations'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='constat',
            field=models.TextField(default='RAS', verbose_name='Constat sur terrain (non-conformités)'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='date_inc',
            field=models.DateField(verbose_name="Date de l'événement"),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='env_animal',
            field=models.CharField(default='RAS', max_length=200, verbose_name='Environnement Animal'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='env_atmospherique',
            field=models.CharField(default='RAS', max_length=200, verbose_name='Environnement Atmosphérique'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='env_humain',
            field=models.CharField(default='RAS', max_length=200, verbose_name='Environnement Humain'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='env_industriel',
            field=models.CharField(default='RAS', max_length=200, verbose_name='Environnement Industriel'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='env_vegeta',
            field=models.CharField(default='RAS', max_length=200, verbose_name='Environnement Végétal'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='fait_apres',
            field=models.TextField(blank=True, null=True, verbose_name="Faits et paramètres après l'incident"),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='fait_avant',
            field=models.TextField(verbose_name="Faits et paramètres avant l'incident"),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='heure_inc',
            field=models.TimeField(verbose_name="Heure de l'événement"),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='impact_param_qp',
            field=models.CharField(max_length=200, verbose_name="Impact sur paramètres QP (ex: 224 MWh d'END)"),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='mes_exploitation',
            field=models.CharField(default='RAS', max_length=200, verbose_name='Mesures conservatoires (Exploitation)'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='mes_maintenance',
            field=models.CharField(default='RAS', max_length=200, verbose_name='Mesures conservatoires (Maintenance)'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='num_inc',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='N° Fiche'),
        ),
        migrations.AlterField(
            model_name='collecteincident',
            name='reprise_client',
            field=models.CharField(max_length=200, verbose_name='Détails sur la reprise de la clientèle'),
        ),
    ]
