# Generated by Django 5.2.4 on 2025-08-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incident_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionmenee",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cause",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="collecteincident",
            name="num_inc",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="equipeanalyse",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="lieu",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ouvrage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
