# Generated by Django 5.2.4 on 2025-08-08 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0002_collecteincident_objet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipeanalyse',
            name='incident',
        ),
        migrations.AddField(
            model_name='equipeanalyse',
            name='analyse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='incident_app.analyseincident'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='incident_app.collecteincident'),
        ),
        migrations.AlterField(
            model_name='recommandationanalyse',
            name='analyse_inc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='incident_app.analyseincident'),
        ),
        migrations.AlterField(
            model_name='recommandationanalyse',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recommandationanalyse',
            name='delai',
            field=models.DateField(blank=True, null=True),
        ),
    ]
