# Generated by Django 5.2.4 on 2025-08-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0003_remove_equipeanalyse_incident_equipeanalyse_analyse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acteur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expertise', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='analyseincident',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name="Conclusion de l'analyse"),
        ),
    ]
