# Generated by Django 5.2.4 on 2025-08-08 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_app', '0004_acteur_expertise_analyseincident_conclusion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyseincident',
            name='equipement',
        ),
        migrations.RemoveField(
            model_name='analyseincident',
            name='lieu',
        ),
        migrations.RemoveField(
            model_name='analyseincident',
            name='ouvrage',
        ),
        migrations.AlterField(
            model_name='acteur',
            name='acteur',
            field=models.CharField(max_length=100, verbose_name='Acteur'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='cause',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident_app.cause', verbose_name='Cause Principale'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='complt_equip_concerne',
            field=models.TextField(verbose_name="Compléments sur l'équipement concerné"),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='complt_equipment',
            field=models.TextField(verbose_name="Compléments sur la famille d'équipement"),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='complt_espace_env',
            field=models.TextField(verbose_name="Compléments sur l'espace et environnement"),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='constat',
            field=models.TextField(verbose_name='Précisions obtenues (Cause, effet, défaillance)'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='date_analyse',
            field=models.DateField(verbose_name='Date analyse'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='heure_dbt_analyse',
            field=models.TimeField(verbose_name="Heure de début d'analyse"),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='heure_dbt_constat',
            field=models.CharField(default='RAS', max_length=100, verbose_name="Constats/Tranche d'heure début"),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='heure_fin_analyse',
            field=models.TimeField(verbose_name="Heure de fin d'analyse"),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='heure_fin_constat',
            field=models.CharField(default='RAS', max_length=100, verbose_name="Constats/Tranche d'heure fin"),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='illustrations/', verbose_name='Illustration'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='impact_autre',
            field=models.CharField(max_length=200, verbose_name='Autres impacts (environnement, image…)'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='impact_cout',
            field=models.CharField(max_length=200, verbose_name='Impact en Coûts et durées'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='impact_nip',
            field=models.CharField(max_length=200, verbose_name='Impact NIP'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='impact_nod',
            field=models.CharField(max_length=200, verbose_name='Impact NOD'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='impact_tmc',
            field=models.CharField(max_length=200, verbose_name='Impact TMC'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='incident_app.collecteincident', verbose_name='Incident Concerné'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='jour_constat',
            field=models.CharField(default='RAS', max_length=100, verbose_name='Constats/Jours'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='list_acteurs',
            field=models.TextField(blank=True, verbose_name="Acteurs au moment de l'incident"),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='list_expertise',
            field=models.TextField(blank=True, verbose_name="Expertises utiles pour l'analyse"),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='repartition',
            field=models.CharField(max_length=100, verbose_name='Répartition (END, ...)'),
        ),
        migrations.AlterField(
            model_name='analyseincident',
            name='saison_constat',
            field=models.CharField(default='RAS', max_length=100, verbose_name='Constats/Saisons'),
        ),
        migrations.AlterField(
            model_name='equipeanalyse',
            name='analyse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='incident_app.analyseincident', verbose_name='Analyse Associée'),
        ),
        migrations.AlterField(
            model_name='equipeanalyse',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='equipeanalyse',
            name='role',
            field=models.CharField(max_length=100, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='equipeanalyse',
            name='structure',
            field=models.CharField(max_length=100, verbose_name='Structure'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='expertise',
            field=models.CharField(max_length=100, verbose_name='Expertise'),
        ),
        migrations.AlterField(
            model_name='recommandationanalyse',
            name='action',
            field=models.CharField(max_length=200, verbose_name='Action recommandée'),
        ),
        migrations.AlterField(
            model_name='recommandationanalyse',
            name='analyse_inc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='incident_app.analyseincident', verbose_name='Analyse Associée'),
        ),
        migrations.AlterField(
            model_name='recommandationanalyse',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût estimé'),
        ),
        migrations.AlterField(
            model_name='recommandationanalyse',
            name='delai',
            field=models.DateField(blank=True, null=True, verbose_name='Délai'),
        ),
        migrations.AlterField(
            model_name='recommandationanalyse',
            name='responsabilite',
            field=models.CharField(max_length=100, verbose_name='Responsabilité'),
        ),
        migrations.AlterField(
            model_name='suiviincident',
            name='commentaire_efficacite',
            field=models.TextField(blank=True, null=True, verbose_name="Commentaire sur l'efficacité"),
        ),
        migrations.AlterField(
            model_name='suiviincident',
            name='commentaire_tenue_delai',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire sur les délais'),
        ),
        migrations.AlterField(
            model_name='suiviincident',
            name='efficacite_action',
            field=models.BooleanField(verbose_name='Efficacité des actions (6 mois/3 ans)'),
        ),
        migrations.AlterField(
            model_name='suiviincident',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident_app.collecteincident', verbose_name='Incident Concerné'),
        ),
        migrations.AlterField(
            model_name='suiviincident',
            name='tenue_delai',
            field=models.BooleanField(verbose_name='Tenue des délais opérationnels convenus'),
        ),
    ]
